version: "3.8"

networks:
  network:

volumes:
  cache:

services:

  redis:
    platform: linux/amd64
    image: redis:7.0
    command: redis-server
    ports:
      - 6379:6379
    volumes:
      - cache:/data
    networks:
      - network