version: "3.8"

networks:
  network:

volumes:
  cache:

services:

    redis:
      platform: linux/amd64
      container_name: redis
      image: redis:7.0
      command: redis-server --requirepass ${REDIS_PASSWORD}
      ports:
        - 6379:6379
      volumes:
        - cache:/data
      depends_on:
        php:
          condition: service_started
      networks:
        - network